# Generated by Django 5.0.7 on 2024-07-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0002_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('name', models.CharField(max_length=25, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripcion')),
                ('date', models.DateField(verbose_name='Fecha Prestamo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro', verbose_name='Libro')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha Devolucion')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.prestamo', verbose_name='Prestamo')),
            ],
        ),
    ]
