# Generated by Django 5.0.7 on 2024-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='front',
            field=models.ImageField(blank=True, null=True, upload_to='libro', verbose_name='prtada'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='contry',
            field=models.CharField(max_length=30, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=30, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='publicacion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='title',
            field=models.CharField(max_length=30, verbose_name='titulo'),
        ),
    ]
